### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by aleksandar-todorovic** [emctague/fortune#4]
Output:

```
/home/r3bl/dev/fortune/index.js:13
    let fortune = child_process.execSync("fortune -a").toString();
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

Sysinfo:

* OS: Ubuntu 17.04
* `node`: v4.7.2
* `npm`: 3.5.2

**Comment by emctague** [comment]
You're using a painfully outdated version of node, probably because Ubuntu ships an old one.

Either:

 * Run node with the `--harmony` flag.
 * Install the latest version - see [here](https://askubuntu.com/questions/49390/how-do-i-install-the-latest-version-of-node-js)

**Comment by aleksandar-todorovic** [comment]
Wow, you're right. The version Ubuntu ships _is_ painfully outdated. After upgrading from 4.7.2 to 7.10.0, this got fixed.

Sorry, wasn't aware that the node ecosystem on Ubuntu is so fucked up.

**Comment by emctague** [comment]
No problem, I'm glad you've noticed that it's outdated. I had the same trouble when I used Ubuntu, too.
